### ISSUE TITLE
<a id="ContextButton">≡</a><br /> will write <a id="ContextButton">??/a><br />

### ISSUE THREAD

**Issue by lee-yunseok** [renpy/renpyweb#1]
**renpy-shell.html**,

`<a id="ContextButton">≡</a><br />` button line will write `<a id="ContextButton">??/a><br />`.

**Comment by Beuc** [comment]
Thanks for the report!
I guess this symbol is not available in your default font.
I'm thinking of replacing it with an inline image.

**Comment by lee-yunseok** [comment]
No problem with you? I think this is an build error. When building a web app, the symbol will broken code. Is it affected by system fonts?

**Comment by Beuc** [comment]
No problem here.
Can you post a screenshot so I better understand what's happening?

**Comment by lee-yunseok** [comment]
When I built with renpyweb, the **symbol will bronken in the index.html** like below.

![notepad++_2019-07-03_00-43-22](https://user-images.githubusercontent.com/5509466/60526621-aa6dfc00-9d2b-11e9-9432-f59bdc966603.png)

So I have to modify the code in index.html manually as a symbol.

**Comment by Beuc** [comment]
Make sure you are editing it as a UTF-8 file (as set in the html meta-data).
By screenshot, I meant a screenshot of the browser window :)

**Comment by Beuc** [comment]
Also can you try with `&#8801;` instead of the symbol? This would solve charset issues.

**Comment by lee-yunseok** [comment]
I mean, if I build project in renpy using renpyweb, **the code of index.html will bronken** like my attached above. **So I have to modify ?? to ≡<**.

**Comment by Beuc** [comment]
OK, so:
- I can't reproduce your problem, it works fine for me with the latest Ren'Py 7.3.2 (and all other versions)
- I suspect the HTML is fine, but you read it with the wrong charset

What we can do: please give me:
- the exact Ren'Py version you're using
- your unmodified index.html with the error so I can download it
- a screenshot of your browser when there's the error

**Comment by lee-yunseok** [comment]
* Ren'Py 7.3.2.320, Windows 10
* [index.html(zip)](https://github.com/renpy/renpyweb/files/3352045/index.zip)
* screenshot below:

![chrome_2019-07-03_04-42-30](https://user-images.githubusercontent.com/5509466/60541640-0137fd80-9d4d-11e9-914a-42eed32a93b2.png)

**Comment by Beuc** [comment]
Thanks a lot!
Does it work better with this? (place it in `renpy-7.3.2/launcher/game/web.rpy`)
[web.zip](https://github.com/renpy/renpyweb/files/3352182/web.zip)

**Comment by lee-yunseok** [comment]
Yes, the error is resolved.

**Comment by Beuc** [comment]
Thanks for testing!
I added the `web.rpy` fix in Ren'Py itself, and also used `&#8801;` just in case.

**Comment by lee-yunseok** [comment]
Thank you for your work, Beuc.
