### ISSUE TITLE
Splitting the zip

### ISSUE THREAD

**Issue by sdreher-techfak** [renpy/renpyweb#12]
Hey, I'm currently trying to upload a game to itch and it doesn't accept files that are >100mb. Is there a way to split the game.zip into a split zip or several regular zips and have everything still work?

Thanks for all the hard work!

**Comment by Beuc** [comment]
Hi, check the F.A.Q. on size / progressive download :)
https://renpy.beuc.net/#faq

**Comment by sdreher-techfak** [comment]
Yeah, I read the FAQ and was hoping I could just split up the zip, since the overall project size isn't close to itch's limits and it's only the fact that it sees the single zip and goes "well a single file shouldn't be this big". And since the zip is unpacked for the game to run anyways, I thought maybe the program could be adjusted to unzip a split zip instead of a single one, which would fix it.

I saw the bit in the FAQ where it said "(alternatively you can start your game by adding ?game=game.xyz as explained in Including more than one game.)" and thought that if you can have more than one game, then having 2 zips is maybe an option, but then I couldn't find the bit where it's explained how to do so.

Thanks for the quick answer anyways, I'll probably just split it into the different routes if I do decide to go ahead with a web version!

**Comment by Beuc** [comment]
You seem to have missed the "progressive download" bit.

**Comment by sdreher-techfak** [comment]
Ah, I didn't know it created several smaller zip files! I thought it just made it so while the game is running, the client downloads only parts of the game as necessary (performance isn't my issue, it's literally just itch.io not liking that the game is in a single zip).
I'll see which of the options is the easiest then, as it's just a silly fangame.

Still, thanks for all the answers!

**Comment by Beuc** [comment]
Progressive download creates a smaller .zip by storing large images / sounds outside of it.
I clarified the F.A.Q. a little.
I'm closing this issue because there is already a working, general-purpose fix for it :)
