### ISSUE TITLE
New version of safari on iPad (iPadOS 14.5.1) and Mac not working with Renpy

### ISSUE THREAD

**Issue by chesnay** [renpy/renpyweb#14]
Since the update of safari on iPad (iPadOS 14.5.1), Renpyweb is not working and there is an error message, when a game is launched:
Error: RangeError: Maximum call stack size exceeded. (See Javascript console for details)

There appears to be a similar issue on the latest version of Safari on Mac (reported on MacBook Pro). My version of Safari on my Mac mini is not as up to date and therefore I have not encountered the issue on the Mac mini yet.

If you go on the website of renpyweb, and try the demo you will be able to see the error message: https://renpy.beuc.net

**Comment by renpytom** [comment]
This is a problem with mobile safari. Recent versions of Ren'Py address this by inviting the player to report this to Apple. There's nothing I can do on my end, so I'm closing this.
