### ISSUE TITLE
Dissolve Shader issues on renpy web 7.4.5

### ISSUE THREAD

**Issue by Emmerald** [renpy/renpyweb#15]
Using the Dissolve transition via the python constructor gives an error.

![image](https://user-images.githubusercontent.com/85029464/120076430-657cac80-c09d-11eb-85e7-b34b4906b5ac.png)

There are other tracebacks, but the above should be enough, and I refuse to post the others due to the privacy bug.

**Comment by renpytom** [comment]
I believe this was the blur issue fixed by renpy/renpy@f6ff59350123fba9f0f24d93bce5f0a81762bb9f .
