### ISSUE TITLE
Privacy issue with all RenpyWeb builds. Developer's filepath is kept

### ISSUE THREAD

**Issue by Emmerald** [renpy/renpyweb#16]
When building with renpyweb, the traceback includes the builder's renpy filepath.

Let's say your renpy was in C:/Users/Emmerald/renpy-7.4.5-sdk/

This would appear in the traceback.

I don't need to spell out why this is a massive privacy violation. From inspecting the zip, things seem to have their correct filepaths - so where has this traceback issue come from?

![image](https://user-images.githubusercontent.com/85029464/120076750-16d01200-c09f-11eb-9735-f5b474ff5f84.png)

 This bug report came from a user, so it wasn't even on my own machine.

**Comment by renpytom** [comment]
It looks like you somehow caused the .pyc files to be recompiled, which includes the full path into them. I'll look and see if I can somehow elide this.

**Comment by Andykl** [comment]
As a solution, put the SDK in the root of the drive.
