### ISSUE TITLE
Inability to import python modules

### ISSUE THREAD

**Issue by DarkTl** [renpy/renpyweb#2]
An attempt to import module causes an error in browser, but not on pc/mac/mobile devices.

code:
import logging

error in browser:
ImportError: No module named logging

**Comment by Beuc** [comment]
The web Python environment is pretty minimal for size and compatibility reasons.
(see the "size" entry in the F.A.Q. https://renpy.beuc.net/#faq for more details and a work-around to add your own modules)

If there's a rationale for a module's usage and if it's easy enough to add, I'll consider including it directly.

**Comment by DarkTl** [comment]
Doesn't seem to be working, unless I do something wrong. 
I added the logging .pyo to game/python-packages, and it presents in the web archive too now. But importing it causes the very same error.

We can live without logging module, it's just for testing, but we also use stuff like pygame and collections modules, those cannot be easily replaced.

**Comment by Beuc** [comment]
AFAIU Ren'Py only loads .py (not-compiled) files from `game/python-packages`.
The F.A.Q. recommends placing additional .pyo in `/lib/python2.7` - or maybe you could adjust you sys.path.

pygame is a requirement for Ren'Py so it will be there :)
Let me know how this works.

**Comment by DarkTl** [comment]
Ah, yes it works. Thanks for the support!
