### ISSUE TITLE
ImportError: No module named httplib

### ISSUE THREAD

**Issue by mschenone** [renpy/renpyweb#20]
Hi,
when running the code below:

```
init python:

    import urllib3
```
ren-py reports the message:

ImportError: No module named httplib

Looking around, it sounds like the issue arises when running the code with Python3 instead of Python2.

Where does the web application look for the python interpreter? is it possible to set it?

Referring to the docker recipe described by @stephwag in https://github.com/stephwag/renpyweb-docker the web application is ran or may be ran using Python 3:

```
docker run -p 8000:8000 \
-v /path/to/your/game:/renpyweb/renpy/web/ \
stephwag/renpyweb python3 -m http.server 8000
```

Does the web server environment determines which python version is used by the web application?

Thanks!

[log.txt](https://github.com/renpy/renpyweb/files/7069355/log.txt)

**Comment by r00tical** [comment]
Hello Tom,

I forgot to mention that the project is working as expected when launched from Ren'Py. 

I just printed some information to investigate the Python runtime in the browser:

```
Python version:  2.7.18 (default, Jul 19 2021, 00:02:06) 
[GCC Clang 13.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-githu
Python paths:  [u'/', '.', '/', '/lib/python27.zip', '/lib/python2.7', '/lib/python2.7/plat-emscripten', '/lib/python2.7/lib-tk', '/lib/python2.7/lib-old', '/lib/lib-dynload', '/lib/python2.7/site-packages', '/']

/lib/python2.7:
Cookie.pyo
Queue.pyo
StringIO.pyo
UserDict.pyo
UserList.pyo
UserString.pyo
__future__.pyo
_abcoll.pyo
..
hashlib.pyo
heapq.pyo
hmac.pyo
imghdr.pyo
importlib
inspect.pyo
...
```
The issue is not due to a wrong runtime version, but it looks like httplib is really missing from the library paths.

**Comment by renpytom** [comment]
Sorry,. must have been a bit tired when I first responded. The issue here is that renpyweb doesn't support the application making http requests, and so the libraries to do so aren't included. (This is tied to limitations of web browsers, than have a very different networking model than real processes do.)

**Comment by r00tical** [comment]
What about the Javascript implementation below? it seems to work

https://github.com/renpy/renpyweb/blob/master/utils/asyncrequest.rpy

**Comment by r00tical** [comment]
The test code below is working as expected:
```

  label start:

    "working test start"
    $ req = AsyncRequest()
    $ req.send('http://127.0.0.1:3000/api/v1/resources/gaming_engine/characters?story_id=1')
    $ timer = 0
    while not renpy.in_rollback() and req.isAlive():
        $ timer += 0.1
        show text "request in progress [timer]"
        pause 0.1
    $ ret = 'rollback'
    if req.getError():
        $ ret = req.getError()
    else:
        $ ret = req.getResponse()
    hide text
    "ret=[ret!q]"
    "test end"
```

On the contrary, calling a function  - which implements the same commands - returns an empty responseText:
 
```
label start:

    "unhappy test start"
    $ ret = async_get('http://127.0.0.1:3000/api/v1/resources/gaming_engine/characters', {'story_id':1})
    "ret=[ret!q]"
    "test end"
```
where async_get is defined below:

```
init python:

    import json
    import os

    def async_get(url, params):
        if renpy.emscripten:    # renpyweb

            req = AsyncRequest()
            url = url + "?" + urlencode(params)

            req.send(url)

            if req.getError():
                return req.getError()
            else:
                ret = {
                    "status" : 200,
                    "data": req.getResponse()
                }
```
The AsyncRequest send method completes the get successfully (status 200), but the temporary file created to save the output is not available to the other methods. It looks like a scope issue, but I can't find a road in there.  Any idea?

Thanks a lot!
