### ISSUE TITLE
Homepage is down

### ISSUE THREAD

**Issue by Tey** [renpy/renpyweb#21]
The site at https://renpy.beuc.net/ does not work (anymore?) because there is not DNS entry for `renpy.beuc.net`. Dunno if this concerns this project or only @Beuc though.

**Comment by Tey** [comment]
The project is probably not abandoned as @renpytom still seems to be working on it, but the original author (and maybe main maintainer) @beuc has been silent both on Github and his blog for months now. Maybe he decided to change his life and went to live in communion with nature away from this digitalized material world... or something worse 😧

Anyway, the website is him so it will probably not be fixed anytime soon. The [latest archive](https://web.archive.org/web/20210303225842/https://renpy.beuc.net/) from the wayback machine seems to be complete enough. Also, renpyweb is fully integrated into Renpy now, so there isn't really a need for that website anymore. Maybe the references to this website should be removed from the repository then?

**Comment by renpytom** [comment]
This looks like it's been done.
