### ISSUE TITLE
Problem importing queue classes.

### ISSUE THREAD

**Issue by Emmerald** [renpy/renpyweb#22]
There seems to be an issue instantiating imported classes from queue in the web build of renpy.

https://media.discordapp.net/attachments/286633898581164032/925858531511521300/unknown.png

To reproduce:
- Load a fresh project.
- Somewhere, insert:
```
init python:
    from queue import PriorityQueue
    myqueue = PriorityQueue()

```

Build for web, and encounter above error. Untested with other implementations of Queue.

**Comment by renpytom** [comment]
I believe this has been fixed, as mentioned above.
