### ISSUE TITLE
ImportError: No module named renpy.bootstrap

### ISSUE THREAD

**Issue by neobenedict** [renpy/renpyweb#26]
Using latest nightly builds of renpy 8 and renpyweb and the tutorial project, renpyweb fails to load with error ImportError: No module named renpy.bootstrap.

(windows 10)

**Comment by renpytom** [comment]
The Web beta isn't going to work in Ren'Py 8. (It'll be in 7.5, and back in 8.1.) I'll disable the button to reduce confusion.
