### ISSUE TITLE
How to make use of the fix for: "Error: Uncaught RangeError: Maximum call stack size exceeded" ?

### ISSUE THREAD

**Issue by Bobyteal** [renpy/renpyweb#30]
I have successfully followed the tutorial on the website: https://kandi.openweaver.com/html/renpy/renpyweb
This helped me get a "renpy-build" repertory inside "user" (me), this renpy build should contain the fix I believe? the version Renpy 7.4.10 creates the build with no problem with the up to date "renpy-build" repertory but it still gets the error.

Sorry if I'm misunderstanding something, just trying to be up to date and apply the fix, which is huge for users of renpy web (not all of us can update to the most recent version of Renpy which can break projects). Thank you for the awesome work on the renpyweb branch and hoping something can be done to fix chrome induced problem even in earlier builds.

**Comment by renpytom** [comment]
Just grab Ren'Py 7.5 from renpy.org.

**Comment by Bobyteal** [comment]
I tried 7.5, the error seems to be gone, but now getting this one: 
"Error: Uncaught ReferenceError: volume is not defined (see JavaScript console for details)"
Is there any way to fix the web error for previous build, is there a line to change somewhere or a simple fix affecting only the renpyweb. many of us can't change to 7.5 because of risk of breaking projects, I suspect most projects in the previous years for web will simply cease to function forever...

**Comment by renpytom** [comment]
Do you have an example of the Uncaught ReferenceError issue? I'd expecially like to know which browser you're using, and what the lines in the Javascript console look like. 

All fixes will be going into 7.5/8.0, not older versions of Ren'Py.

**Comment by Bobyteal** [comment]
Here is a partial log of the error, the log is ten pages long and the project was run on google chrome,  this is about 1/4 of it, let me know if you want everything as well:
![HUD31_timesetting](https://user-images.githubusercontent.com/78823063/172022208-4221f260-e654-4935-847b-784ccb2c26b9.png)
I'm not sure what went wrong
(bummer for only >7.5 :( )

**Comment by renpytom** [comment]
7.5 is really good, and most games should run unchanged on it. 

I think the error that I'll need is towards the bottom, it should mention Uncaught ReferenceError in it.

**Comment by Bobyteal** [comment]
Ah alright, here is the bottom
![HUD31_timesetting](https://user-images.githubusercontent.com/78823063/172022558-91f3617d-17ab-442f-a96a-6d2cdcd5dd43.png)
:
No problem, I have absolutely no doubt that 7.5 is great, you are killing it. It's just for some projects like me that I think use bugs to run or a weird kirks of an older version and can't really update, it's the same when unity/engine update, it's sometimes complicated to update a project in the middle without breaking things, but well it's just web support lost, don't want to appear whiney and keep up the great work
