### ISSUE TITLE
Error while installing on OSX Ventura

### ISSUE THREAD

**Issue by marimeireles** [renpy/renpyweb#37]
Getting the following error when trying to build:

```
emsdk-toolchain.web-wasm already finished.
embuilder-toolchain.web-wasm already finished.
unpack-nasm.host running in .../dev/renpy-build/tmp/build/nasm.host ...
tar: Option -a is not permitted in mode -x
unpack-nasm.host: process failed with 1.
args: ['tar', 'xaf', '.../dev/renpy-build/source/nasm-2.14.02.tar.gz']
  File ".../dev/renpy-build/./build.py", line 204, in <module>
    main()
  File ".../dev/renpy-build/./build.py", line 200, in main
    args.function(args)
  File ".../dev/renpy-build/./build.py", line 122, in build
    task.run(context)
  File ".../dev/renpy-build/renpybuild/task.py", line 97, in run
    self.function(context)
  File ".../dev/renpy-build/tasks/nasm.py", line 12, in unpack
    c.run("tar xaf {{source}}/nasm-{{version}}.tar.gz")
  File ".../dev/renpy-build/renpybuild/context.py", line 328, in run
    renpybuild.run.run(command, self, verbose, quiet)
  File ".../dev/renpy-build/renpybuild/run.py", line 403, in run
    traceback.print_stack()
```

I've built the latest version of emscripten locally:

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.31 (e88336121cfe6da4a96c88e46f314552f07dfed0)
clang version 17.0.0 (https://github.com/llvm/llvm-project 1142e6c7c795de7f80774325a07ed49bc95a48c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: .../dev/emsdk/upstream/bin
```

I wonder if that's the issue?

**Comment by marimeireles** [comment]
Will be looking into it now but, thought I might open an issue anyway in case someone bump into in the future or knows the solution.
Thanks!

**Comment by renpytom** [comment]
Are you trying to actually build on OSX? Since renpy-build is only meant to work on Ubuntu 22.04.

**Comment by marimeireles** [comment]
Ahhr yes. That's what I'm trying to do. Sorry I missed that.
The error disappeared and I started getting some weird compiler version problems instead
I think that explains it! 😅

Ahhm I'm trying to make it work with [pyscript](github.com/pyscript/pyscript/), I think it'd be awesome! :D
To run it in the web, but also seems like a veery long effort. Let's see!

Cheers and closing this one.

**Comment by renpytom** [comment]
Ren'Py already runs on the web, though. (Including Ren'Py 8, as of the nightly builds.)

**Comment by marimeireles** [comment]
Hum, yeah maybe I should try it on the web.
The reason why I wanted to integrate with pyscript is to extend it with python, but might not be super relevant or interesting.
