### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by oxr463** [renpy/renpyweb#4]
I don't see this repository in the license list here: https://www.renpy.org/doc/html/license.html

**Comment by Beuc** [comment]
The files in this repository carry copyright and license notices.
For Ren'Py's license.html file, this looks like an oversight and you may file a bug against https://github.com/renpy/renpy/blob/master/sphinx/source/license.rst :)

**Comment by Beuc** [comment]
I see this was fixed in Ren'Py master, closing.
