### ISSUE TITLE
Warning: write error: FS error

### ISSUE THREAD

**Issue by remarkablemark** [renpy/renpyweb#41]
I uploaded a Ren'Py game to [Newgrounds](https://www.newgrounds.com/portal/view/945558) but keep getting the error:

![Screenshot 2024-08-27 at 7 57 52 PM](https://github.com/user-attachments/assets/7703a86b-3edb-4f00-8357-8883702caaec)

![Screenshot 2024-08-27 at 7 57 37 PM](https://github.com/user-attachments/assets/0fffeadd-e413-4274-a392-f398b5e979fe)

Any suggestions on how I can fix or suppress this error?

Update: found the related issue https://github.com/renpy/renpy/issues/5725

**Comment by renpytom** [comment]
It's fixed in the nightly builds and the 8.3.1 prerelease.
