### ISSUE TITLE
How to compile game from CI/CD pipeline

### ISSUE THREAD

**Issue by oxr463** [renpy/renpyweb#5]
I am using GitLab CI/CD, but it could also apply to GitHub Actions or anything really.

I can't seem to figure out how to trigger this from the launcher via the terminal.

**Comment by Beuc** [comment]
I don't think this is implemented at the moment. distribute-game.sh provides some automation but has documented limitations.

**Comment by oxr463** [comment]
That's a good hint. Once I figure it out I'll push a doc or something.
