### ISSUE TITLE
spinner and progress colors?

### ISSUE THREAD

**Issue by SavedByZero** [renpy/renpyweb#6]
I need to customize the style for the spinner and  preloader progress bar, but I don't see those values in the html file.  The color values that I see are rgb(40,40,40) and rgb(120,120,120), which do not match what shows up (progress bar looks green).

**Comment by Beuc** [comment]
Hi. Where is the question, and the politeness? :)

**Comment by SavedByZero** [comment]
Okay, my tone was admittedly plain and stark, but otherwise extremely neutral.

Passive aggressive answers like yours aren’t exactly the way to make people more polite, if that’s really what you were trying to achieve. I suspect you know what I was asking but I think I figured it out so no worries. Sorry to disturb you, chief.
