### ISSUE TITLE
Is it possible to divide the download data?

### ISSUE THREAD

**Issue by suihakei** [renpy/renpyweb#7]
I am Japanese and my English is poor. I'm sorry.

I recently started using Renpy.
It's cross-platform, especially the ability to launch on the web browser.

## Questions
I'm remaking my old game with Renpy.
And I want to make it playable in the browser.
However, my game was about 500 MB and I got an error in my web browser. (Android10 Brave browser)

For example, is it possible to download data for each episode?
(After reading the first episode, download it before starting the second.)

I think Renpy is a great piece of software.
I'm rooting for you.

Thank you!

**Comment by Beuc** [comment]
Hi!
The development version has "progressive download".
Did you try the "RED" binaries from https://renpy.beuc.net/ ?

**Comment by suihakei** [comment]
Thank you for your reply.
I'd like to try RenPyWeb Early Downloads!
Thank you!
